### ISSUE TITLE
Add Feature Card component

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#220]
Create equivalent of Design System's Feature Card component

[[Call it Feature Card](https://designsystem.webstandards.ca.gov/components/feature-card/readme/)](https://designsystem.webstandards.ca.gov/components/feature-card/readme/)

Screenshot example:
![Screen Shot 2022-03-25 at 8 49 44 AM](https://user-images.githubusercontent.com/31669748/160155165-5731489e-9506-4112-bf12-d6e645a6f76d.png)

**Comment by kkoryaka** [comment]
Notify @ashleydraper when it's done

**Comment by kkoryaka** [comment]
@Courtney-Chittock please review: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/feature-card.html

**Comment by Courtney-Chittock** [comment]
@kkoryaka the feature card is not stacking correctly in mobile. 
![image](https://user-images.githubusercontent.com/99773875/174151298-0b5e7752-0cbc-4bdb-81e5-0df39c2f093c.png)

Also, we should smooth out the layout for some of these transitional widths, where the narrower columns make the content look very awkward:
![image](https://user-images.githubusercontent.com/99773875/174151427-3cb7678d-e107-433c-af2d-20f6ab78d73b.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock.  Makes sense. Thanks

**Comment by kkoryaka** [comment]
@Courtney-Chittock this one should be fixed: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/feature-card.html

**Comment by Courtney-Chittock** [comment]
@kkoryaka the stacking order looks good. The other issues remain. Maybe we can discuss at a Design System meeting?

**Comment by ashleydraper** [comment]
The specific bug identified in this issue appears to be fixed. Recommend we close the issue.

**Comment by kkoryaka** [comment]
@Courtney-Chittock  THis is not design system, remember that we are trying to make it look like DS. We are using bootstrap breakpoints and we need to work around those. Please let me know exactly what your concerns are. You mentioned above that in some breakpoints the text column width look too narrow. I changed column width for medium breakpoint (where window width starts from 768px to 991px) to the half. Now it is like this. Would you like to chage it to some other width?
![Screen Shot 2022-07-05 at 10 33 18 AM](https://user-images.githubusercontent.com/31669748/177385041-8b95ff26-b752-4087-a003-dcbe2ff0b583.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka this component needs to be refined to control how the layout reflows at certain breakpoints, but this is not the project for that. Can you please add this to the Design System backlog? Or maybe @yesenia-gtz can?

**Comment by kkoryaka** [comment]
@Courtney-Chittock I have updated image cover behavior. Now it should stretch to the edges of the column. If you see other improvements as far as column width and breakpoints goes let me know,

**Comment by Courtney-Chittock** [comment]
MUCH improved. Nice work. I think we can close this out.
